# -*- coding: utf-8 -*-
"""keras ocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wAYqURj2hwP96ezDwh-eNdhKXUzGJK77
"""

! pip install -q keras-ocr

! pip install git+https://github.com/faustomorales/keras-ocr.git#egg=keras-ocr

import keras_ocr
import matplotlib.pyplot as plt

pipeline = keras_ocr.pipeline.Pipeline()

images = [
    keras_ocr.tools.read(img) for img in ['/content/7.jpg',
                                          '/content/bedroom.jpg',
                                          '/content/person2.jpg',
                                          '/content/PAN_Card.jpg',
                                          '/content/stall.jpg']
]

prediction_groups = pipeline.recognize(images)

predicted_image = prediction_groups[0]
for text, box in predicted_image:
    print(text)

predicted_image = prediction_groups[1]
for text, box in predicted_image:
    print(text)

predicted_image = prediction_groups[2]
for text, box in predicted_image:
    print(text)

predicted_image = prediction_groups[3]
for text, box in predicted_image:
    print(text)

predicted_image = prediction_groups[4]
for text, box in predicted_image:
    print(text)

